from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

RAW_DATA_DIR = ROOT / "data/raw"
PROCESSED_DATA_DIR = ROOT / "data/processed"

ORIGINAL_DATA_DIR = RAW_DATA_DIR / "original"
ORIGINAL_CSV = ORIGINAL_DATA_DIR / "styles.csv"
ORIGINAL_IMAGE_LINKS_CSV = ORIGINAL_DATA_DIR / "images.csv"
ORIGINAL_IMAGE_DIR = ORIGINAL_DATA_DIR / "images"
ORIGINAL_STYLE_JSON_DIR = ORIGINAL_DATA_DIR / "styles"

TEACHER_DATA_DIR = RAW_DATA_DIR / "teacher"
TEACHER_TRAIN_DIR = TEACHER_DATA_DIR / "train"
TEACHER_TRAIN_CSV = TEACHER_TRAIN_DIR / "styles_train.csv"
TEACHER_TRAIN_IMAGE_DIR = TEACHER_TRAIN_DIR / "images_train"
TEACHER_TEST_DIR = TEACHER_DATA_DIR / "test"
TEST_CSV = TEACHER_TEST_DIR / "styles_prediction.csv"
TEST_IMAGE_DIR = TEACHER_TEST_DIR / "images_test"

AUDIT_DIR = PROCESSED_DATA_DIR / "audit"
TRAIN_MANIFEST_CSV = PROCESSED_DATA_DIR / "train_manifest.csv"
PREDICTION_MANIFEST_CSV = PROCESSED_DATA_DIR / "prediction_manifest.csv"
LABEL_MAPS_JSON = PROCESSED_DATA_DIR / "label_maps.json"
SPLITS_CSV = PROCESSED_DATA_DIR / "splits.csv"
SPLIT_SUMMARY_JSON = PROCESSED_DATA_DIR / "split_summary.json"
DEVELOPMENT_CLASS_SUMMARY_CSV = PROCESSED_DATA_DIR / "development_class_summary.csv"
NORMALIZATION_JSON = PROCESSED_DATA_DIR / "normalization.json"

RESULTS_DIR = ROOT / "results"
FIGURE_DIR = RESULTS_DIR / "figures"
EDA_FIGURE_DIR = FIGURE_DIR / "eda"
EVIDENCE_DIR = RESULTS_DIR / "evidence"
EDA_EVIDENCE_DIR = EVIDENCE_DIR / "eda"

TARGET_COLUMNS = ("articleType", "season", "gender", "usage")
RANDOM_SEED = 2753
IMAGE_SIZE = 128
PAD_COLOR = (255, 255, 255)
TRAIN_RATIO = 0.70
VALIDATION_RATIO = 0.15
HOLDOUT_RATIO = 0.15
